### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by darconeous** [signalo/signalo#92]
Has any consideration been given to extending this library to support async rust concepts, like [`futures::stream::Stream`](https://docs.rs/futures/0.3.17/futures/stream/trait.Stream.html)?

**Comment by regexident** [comment]
Hi @darconeous, I honestly haven't looked into async support yet, since pretty much all the filters provided by signalo are very lightweight (a necessity of proper real-time support) and most use-cases I've so far been able to think about are strictly serial in nature, making it hard to process concurrently.

Do you have any specific scenario in mind where support for `Stream` would be beneficial?

**Comment by darconeous** [comment]
I was imagining cases where you are demodulating a signal through a pipeline that ultimately ends up emitting values intermittently depending on the signal, like packets. I'm just trying to feel out the problem space a bit better... Perhaps there are better ways to do it.

**Comment by regexident** [comment]
Another issue with adding async support to signalo "today":

Right now we can only use async functions in traits using the [async-trait](https://crates.io/crates/async-trait) crate. And signalo is all about traits.

The async-trait crate however turns `async fn foo() -> Foo;` into something like `async fn foo() -> Pin<Box<dyn Future<Output = Foo>>>`.

Allocating a `Box<T>` for every single value of a signal would be horrendously inefficient.

Once "proper" async functions in traits have landed I'd be more than happy to revisit the topic though.
Thanks for bringing it up @darconeous!
